import type { Command } from 'commander';
import { AGENT_TARGETS, installAgents, type AgentTarget } from '../../agents/install.ts';
import type { ProjectState } from '../../domain/types.ts';
import { assess } from '../../guidance/warnings.ts';
import { nextSteps } from '../../guidance/next-steps.ts';
import { EventLog } from '../../store/event-log.ts';
import { claimCounts, describeEvent, eventLine, pendingProposals, warningLine } from '../format.ts';
import { EXIT } from '../io.ts';
import { CliExit, fail, openLog, parseCount, projectRoot, requireHuman, say, sayJson, splitList, type Env } from '../human.ts';

const INTEGRITY_LINE = 'integrity check FAILED — the log was edited outside cws (run `cws verify`)';

function statusLines(state: ProjectState): string[] {
  const active = state.sessions.find((s) => s.id === state.activeSessionId);
  return [
    `${state.title}  [phase: ${state.phase}]`,
    active ? `Session: ${active.goal}` : 'Session: no active session — `cws session start <goal>`',
    `${state.notes.length} notes, ${claimCounts(state)}, ${state.decisions.length} decisions, ${pendingProposals(state).length} pending proposals`,
  ];
}

async function init(env: Env, title: string[]): Promise<void> {
  requireHuman(env, 'init');
  const log = await EventLog.init(env.io.cwd, title.join(' '));
  say(
    env,
    `Project "${log.state.title}" created.`,
    'Next: capture your raw thoughts with  cws dump "<your raw thoughts>"',
    'and start a work session with  cws session start <goal>',
  );
}

function statusJson(env: Env, log: EventLog): void {
  const state = log.state;
  const active = state.sessions.find((s) => s.id === state.activeSessionId);
  const top = nextSteps(state, 1)[0];
  sayJson(env, {
    title: state.title,
    phase: state.phase,
    session: active ? { id: active.id, goal: active.goal } : null,
    counts: { notes: state.notes.length, claims: state.claims.length, decisions: state.decisions.length, pendingProposals: pendingProposals(state).length },
    integrity: log.integrity.ok ? { ok: true } : { ok: false, brokenAtSeq: log.integrity.brokenAtSeq },
    warnings: assess(state).map((w) => ({ severity: w.severity, code: w.code, message: w.message, refs: w.refs })),
    next: top ? { purpose: top.purpose, title: top.title, reason: top.reason, refs: top.refs } : null,
  });
}

async function status(env: Env, opts: { json?: boolean } = {}): Promise<void> {
  const log = await openLog(env);
  const state = log.state;
  if (opts.json === true) return statusJson(env, log);
  const lines = statusLines(state);
  if (!log.integrity.ok) lines.push(INTEGRITY_LINE);
  const warnings = assess(state);
  if (warnings.length > 0) lines.push('Warnings:', ...warnings.map((w) => `  ${warningLine(w)}`));
  const top = nextSteps(state, 1)[0];
  if (top) lines.push(`Next: ${top.title} → cws prompt 1`);
  say(env, ...lines);
}

async function verify(env: Env): Promise<number> {
  const log = await openLog(env);
  const { ok, brokenAtSeq } = log.integrity;
  if (ok) {
    say(env, `Log intact (${log.events.length} events).`);
    return EXIT.OK;
  }
  say(env, `Integrity check FAILED at event #${brokenAtSeq} — the log was edited outside cws.`);
  return EXIT.INTEGRITY;
}

async function logCommand(env: Env, opts: { limit?: string; session?: string; json?: boolean }): Promise<void> {
  const log = await openLog(env);
  let events = log.events.filter((e) => opts.session === undefined || e.sessionId === opts.session);
  if (opts.limit !== undefined) events = events.slice(-parseCount(env, opts.limit, '--limit'));
  if (opts.json === true) {
    return sayJson(env, {
      events: events.map((e) => ({ seq: e.seq, id: e.id, at: e.at, actor: e.actor, type: e.type, summary: describeEvent(e) })),
    });
  }
  say(env, ...events.map(eventLine));
}

async function installCommand(env: Env, opts: { targets?: string }): Promise<void> {
  const requested = splitList(opts.targets);
  const bad = requested.filter((t) => !(AGENT_TARGETS as readonly string[]).includes(t));
  if (bad.length > 0) fail(env, `error: unknown target ${bad.join(', ')} (choose from ${AGENT_TARGETS.join(', ')})`);
  const targets = requested.length > 0 ? (requested as AgentTarget[]) : undefined;
  const result = await installAgents(projectRoot(env) ?? env.io.cwd, targets ? { targets } : {});
  say(env, ...result.written.map((f) => `wrote   ${f}`), ...result.skipped.map((f) => `skipped ${f} (not generated by cws)`));
}

export function registerProject(program: Command, env: Env): void {
  program.command('init <title...>').description('start a project here').action((t: string[]) => init(env, t));
  program
    .command('status')
    .description('where things stand')
    .option('--json', 'machine-readable output (see docs/cli-json.md)')
    .action((o: { json?: boolean }) => status(env, o));
  program
    .command('verify')
    .description('check the event log for tampering')
    .action(async () => {
      const code = await verify(env);
      if (code !== EXIT.OK) throw new CliExit(code);
    });
  program
    .command('log')
    .description('show recorded events')
    .option('--limit <n>', 'only the last n events')
    .option('--session <id>', 'only events of one session')
    .option('--json', 'machine-readable output (see docs/cli-json.md)')
    .action((o: { limit?: string; session?: string; json?: boolean }) => logCommand(env, o));
  program
    .command('install-agents')
    .description('write AGENTS.md and per-tool prompt wrappers')
    .option('--targets <list>', `comma list of ${AGENT_TARGETS.join(',')}`)
    .action((o: { targets?: string }) => installCommand(env, o));
}
