/**
 * OpenShell sandbox policies, generated from the project.
 *
 * A policy is YAML that says what a sandbox may touch. CWS generates the smallest
 * policy that lets the project work and nothing more:
 *   - the working directory and `/tmp` are writable, system folders are read-only
 *   - the sandbox runs as a non-root user
 *   - outbound network is denied unless the human approved a specific rule
 *
 * Two rules from OpenShell's own guidance are enforced here, because they need an
 * administrator to be safe: no wildcard hosts, and no `protocol: tcp` / `tls: skip`
 * that would bypass application-level inspection.
 */

export const SYSTEM_READ_ONLY = ['/usr', '/lib', '/proc', '/dev/urandom', '/app', '/etc', '/var/log'] as const;
export const SANDBOX_READ_WRITE = ['/sandbox', '/tmp', '/dev/null'] as const;

export interface SandboxNetworkRule {
  host: string;
  port: number;
  /** `rest` gets HTTP method and path rules; omit for a plain TLS connection */
  protocol?: 'rest';
  /** when no method is given: `read-only` (GET/HEAD) or `full` */
  access?: 'read-only' | 'full';
  method?: string;
  path?: string;
  /** the only program allowed to use this rule */
  binary?: string;
}

export interface PolicyOptions {
  rules?: readonly SandboxNetworkRule[];
  readOnly?: readonly string[];
  readWrite?: readonly string[];
  runAsUser?: string;
  runAsGroup?: string;
  /** `hard_requirement` refuses to start the sandbox when the rules cannot be applied */
  landlock?: 'best_effort' | 'hard_requirement';
}

/**
 * Values that survive YAML unchanged. A leading `/` or letter is safe; a leading `*`
 * would look like an alias and is rejected earlier by `validateRule`, so it is quoted.
 */
const PLAIN = /^[A-Za-z/][A-Za-z0-9._/:*+\-]*$/;
const SAFE_METHOD = /^[A-Z]+$/;
const SAFE_HOST = /^(?:\*\.)?[A-Za-z0-9](?:[A-Za-z0-9.-]*[A-Za-z0-9])?$/;

function yamlString(value: string): string {
  return PLAIN.test(value) ? value : JSON.stringify(value);
}

/** `api.github.com:443` → `api_github_com_443`, so the policy stays greppable. */
export function ruleName(rule: SandboxNetworkRule): string {
  const base = `allow_${rule.host.replace(/[^A-Za-z0-9]+/g, '_')}_${rule.port}`;
  const method = rule.method === undefined ? '' : `_${rule.method.toLowerCase()}`;
  return `${base}${method}`.replace(/_+/g, '_').toLowerCase().slice(0, 60);
}

/** Why a rule would be unsafe or malformed, or null when it is fine. */
export function validateRule(rule: SandboxNetworkRule): string | null {
  if (rule.host.trim() === '') return 'the host is empty';
  if (rule.host.includes('*') && !rule.host.startsWith('*.')) return `wildcard hosts are not allowed: ${rule.host}`;
  if (rule.host.includes('*')) return `wildcard hosts are not allowed, name the exact host: ${rule.host}`;
  if (!SAFE_HOST.test(rule.host)) return `not a host name: ${rule.host}`;
  if (!Number.isInteger(rule.port) || rule.port < 1 || rule.port > 65535) return `not a port: ${rule.port}`;
  if (rule.method !== undefined && !SAFE_METHOD.test(rule.method)) return `the method must be upper case letters: ${rule.method}`;
  if (rule.path !== undefined) {
    if (!rule.path.startsWith('/')) return `the path must start with "/": ${rule.path}`;
    if (rule.path.includes('?')) return `paths may not carry query strings: ${rule.path}`;
  }
  if (rule.method !== undefined && rule.path === undefined) return 'a method needs a path';
  if (rule.path !== undefined && rule.method === undefined) return 'a path needs a method';
  if (rule.binary !== undefined && !rule.binary.startsWith('/')) return `the binary must be an absolute path: ${rule.binary}`;
  return null;
}

export function validateRules(rules: readonly SandboxNetworkRule[]): string[] {
  return rules.flatMap((rule) => {
    const problem = validateRule(rule);
    return problem === null ? [] : [problem];
  });
}

function endpointLines(rule: SandboxNetworkRule, indent: string): string[] {
  const lines = [`${indent}- host: ${yamlString(rule.host)}`, `${indent}  port: ${rule.port}`];
  if (rule.protocol === 'rest') lines.push(`${indent}  protocol: rest`);
  lines.push(`${indent}  enforcement: enforce`);
  if (rule.method !== undefined && rule.path !== undefined) {
    lines.push(`${indent}  rules:`, `${indent}    - allow:`, `${indent}        method: ${rule.method}`, `${indent}        path: ${yamlString(rule.path)}`);
  } else {
    lines.push(`${indent}  access: ${rule.access ?? 'read-only'}`);
  }
  return lines;
}

export function buildPolicy(opts: PolicyOptions = {}): string {
  const rules = [...(opts.rules ?? [])].sort((a, b) => ruleName(a).localeCompare(ruleName(b)));
  const lines = [
    '# Generated by cws — edit .cws/integrations.json or re-run `cws sandbox policy`.',
    'version: 1',
    '',
    'filesystem_policy:',
    '  include_workdir: true',
    '  read_only:',
    ...(opts.readOnly ?? SYSTEM_READ_ONLY).map((path) => `    - ${yamlString(path)}`),
    '  read_write:',
    ...(opts.readWrite ?? SANDBOX_READ_WRITE).map((path) => `    - ${yamlString(path)}`),
    '',
    'landlock:',
    `  compatibility: ${opts.landlock ?? 'best_effort'}`,
    '',
    'process:',
    `  run_as_user: ${yamlString(opts.runAsUser ?? 'sandbox')}`,
    `  run_as_group: ${yamlString(opts.runAsGroup ?? 'sandbox')}`,
  ];

  if (rules.length === 0) {
    lines.push('', '# No network access was approved. All outbound traffic is denied.');
  } else {
    lines.push('', 'network_policies:');
    for (const rule of rules) {
      lines.push(`  ${ruleName(rule)}:`, `    name: ${ruleName(rule)}`, '    endpoints:', ...endpointLines(rule, '      '));
      if (rule.binary !== undefined) lines.push('    binaries:', `      - path: ${yamlString(rule.binary)}`);
    }
  }

  return `${lines.join('\n')}\n`;
}

/**
 * `[binary@]host:port[/METHOD:path]`, e.g.
 *   `api.github.com:443`
 *   `/usr/bin/gh@api.github.com:443/PUT:/repos/o/r/contents/docs/**`
 */
export function parseRuleSpec(spec: string): SandboxNetworkRule {
  const trimmed = spec.trim();
  if (trimmed === '') throw new Error('empty rule');

  const at = trimmed.lastIndexOf('@');
  const binary = at === -1 ? undefined : trimmed.slice(0, at);
  const rest = at === -1 ? trimmed : trimmed.slice(at + 1);

  const slash = rest.indexOf('/');
  const hostPort = slash === -1 ? rest : rest.slice(0, slash);
  const tail = slash === -1 ? '' : rest.slice(slash + 1);

  const colon = hostPort.lastIndexOf(':');
  if (colon === -1) return complete({ host: hostPort, port: Number.NaN }, binary);
  const host = hostPort.slice(0, colon);
  const port = Number(hostPort.slice(colon + 1));

  if (tail === '') return complete({ host, port }, binary);
  const methodSplit = tail.indexOf(':');
  if (methodSplit === -1) {
    return complete({ host, port, access: 'read-only' }, binary, `expected METHOD:path after "/", got "${tail}"`);
  }
  return complete({ host, port, protocol: 'rest', method: tail.slice(0, methodSplit), path: tail.slice(methodSplit + 1) }, binary);
}

function complete(rule: SandboxNetworkRule, binary: string | undefined, problem?: string): SandboxNetworkRule {
  if (problem !== undefined) throw new Error(problem);
  const withBinary = binary === undefined || binary === '' ? rule : { ...rule, binary };
  const invalid = validateRule(withBinary);
  if (invalid !== null) throw new Error(invalid);
  return withBinary;
}

export interface PolicyFile {
  /** the policy text itself */
  text: string;
  /** the rules that went into it */
  rules: SandboxNetworkRule[];
}

export function policyFor(rules: readonly SandboxNetworkRule[], opts: Omit<PolicyOptions, 'rules'> = {}): PolicyFile {
  const problems = validateRules(rules);
  if (problems.length > 0) throw new Error(problems.join('; '));
  return { text: buildPolicy({ ...opts, rules }), rules: [...rules] };
}
